/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneodetenis.vistas.Partido;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import torneodetenis.control.PartidoData;
import torneodetenis.control.RankingData;
import torneodetenis.modelo.Conexion;
import torneodetenis.modelo.Jugador;
import torneodetenis.modelo.Partido;
import torneodetenis.modelo.Ranking;
import torneodetenis.modelo.Torneo;

/**
 *
 * @author Santiago
 */
public class vistaTerminarPartido extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaTerminarPartido
     */
    public vistaTerminarPartido() {
        initComponents();
        jcGanador.removeAllItems();
        jcPartido.removeAllItems();
        agregarItemPartido();
        agregarItemJugador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcPartido = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcGanador = new javax.swing.JComboBox<>();
        jtResultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Terminar Partido");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Resultado");

        jcPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPartidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Partido");

        jtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtResultadoActionPerformed(evt);
            }
        });
        jtResultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtResultadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtResultadoKeyTyped(evt);
            }
        });

        jLabel4.setText("Ganador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcPartido, 0, 173, Short.MAX_VALUE)
                    .addComponent(jtResultado)
                    .addComponent(jcGanador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jButton1.setText("Terminar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(146, 146, 146)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Conexion conexion = new Conexion();
            PartidoData td = new PartidoData(conexion);
            RankingData rd = new RankingData(conexion);
            Partido p = (Partido) jcPartido.getSelectedItem();
            Jugador j = (Jugador) jcGanador.getSelectedItem();
            Torneo t = p.getTorneo();
            Ranking r = rd.obtenerRanking(j.getId_jugador(), t.getId_torneo());
            
            if("Terminado".equals(p.getEstado()) || "Por jugar".equals(p.getEstado())  ){
                JOptionPane.showMessageDialog(null, "Su partido ya termino o todavia no comienza");
            }else{
                td.agregarResultado(p, jtResultado.getText(), j);
                rd.sumarPuntos(r, 3);
                JOptionPane.showMessageDialog(null, "El partido termnino correctamente");            
            }
            
            
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion " + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtResultadoActionPerformed

    private void jtResultadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtResultadoKeyReleased
        // TODO add your handling code here:
        activarBotonGuardar();
    }//GEN-LAST:event_jtResultadoKeyReleased

    private void jtResultadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtResultadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtResultadoKeyTyped

    private void jcPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPartidoActionPerformed
        // TODO add your handling code here:
        jcGanador.removeAllItems();
        agregarItemJugador();
    }//GEN-LAST:event_jcPartidoActionPerformed

    private void agregarItemPartido(){
        try{
            Conexion conexion = new Conexion();
            PartidoData td = new PartidoData(conexion);
            
            ArrayList<Partido> torneos = (ArrayList<Partido>) td.obtenerPartidos();
            
            for(int i = 0; i < torneos.size(); i++){
                jcPartido.addItem(torneos.get(i));
            }
            
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion " + ex);
        }
    }
    
    private void agregarItemJugador(){
        try{
            Conexion conexion = new Conexion();
            PartidoData jd = new PartidoData(conexion);
            Partido p = (Partido) jcPartido.getSelectedItem();
            ArrayList<Jugador> jugadores = (ArrayList<Jugador>) jd.obtenerJugadores(p.getId_partido());

            
            for(int i = 0; i < jugadores.size(); i++){
                jcGanador.addItem(jugadores.get(i));
            }
            
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion xd " + ex);
        }
    }
    
    private void activarBotonGuardar(){
       if(jtResultado.getText().isEmpty()){
            jButton1.setEnabled(false);
        }else{
            jButton1.setEnabled(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<Jugador> jcGanador;
    private javax.swing.JComboBox<Partido> jcPartido;
    private javax.swing.JTextField jtResultado;
    // End of variables declaration//GEN-END:variables
}
