/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneodetenis.vistas.Patrocinio;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import torneodetenis.control.JugadorData;
import torneodetenis.control.PatrocinadorData;
import torneodetenis.control.PatrocinioData;
import torneodetenis.control.RankingData;
import torneodetenis.modelo.Conexion;
import torneodetenis.modelo.Jugador;
import torneodetenis.modelo.Patrocinador;
import torneodetenis.modelo.Patrocinio;
import torneodetenis.modelo.Ranking;

/**
 *
 * @author Santiago
 */
public class vistasAgregarPatrocinio extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistasAgregarPatrocinio
     */
    public vistasAgregarPatrocinio() {
        initComponents();
       
        this.agregarItemJugadores();
        jcPatrocinadores.removeAllItems();
        this.agregarItemPatrocinador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcJugador = new javax.swing.JComboBox<>();
        jcPatrocinadores = new javax.swing.JComboBox<>();
        jbPatrocinar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Patrocinio");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Patrocinador");

        jLabel3.setText("Jugador");

        jcJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jcJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jcPatrocinadores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcPatrocinadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jbPatrocinar.setText("Patrocinar");
        jbPatrocinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPatrocinarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(207, 207, 207))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbPatrocinar)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPatrocinar)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPatrocinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPatrocinarActionPerformed
        // TODO add your handling code here:
        try{
            Conexion conexion = new Conexion();
            JugadorData jd = new JugadorData(conexion);
            PatrocinadorData pd = new PatrocinadorData(conexion);
            PatrocinioData pcd = new PatrocinioData(conexion);
            
            Jugador j = (Jugador) jcJugador.getSelectedItem();
            Patrocinador p = (Patrocinador) jcPatrocinadores.getSelectedItem();
            Patrocinio pa = new Patrocinio(j, p);
            RankingData rd = new RankingData(conexion);
            
            pcd.agregarPatrocinio(pa);
            ArrayList<Ranking> rankings = (ArrayList<Ranking>) rd.obtenerRanking();
                    
            for(int i = 0; i < rankings.size(); i++){
                if(rankings.get(i).getJugador().getId_jugador() == j.getId_jugador()){
                    rd.sumarPuntos(rankings.get(i), 1);
                }
            }
            
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion " + ex);
        }
        
        jcPatrocinadores.removeAllItems();
        this.agregarItemPatrocinador();
    }//GEN-LAST:event_jbPatrocinarActionPerformed

    private void jcJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcJugadorActionPerformed
        // TODO add your handling code here:
        jcPatrocinadores.removeAllItems();
        this.agregarItemPatrocinador();
    }//GEN-LAST:event_jcJugadorActionPerformed
    
    private void agregarItemJugadores(){
        try{
            Conexion conexion = new Conexion();
            JugadorData jd = new JugadorData(conexion);
            
            ArrayList<Jugador> jugadores = (ArrayList<Jugador>) jd.obtenerJugadores();
        
            for(int i = 0; i < jugadores.size(); i++){
                jcJugador.addItem(jugadores.get(i));
            }
        
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion " + ex);
        }     
    }
    
    private void agregarItemPatrocinador(){
        try{
            Conexion conexion = new Conexion();
            PatrocinioData pd = new PatrocinioData(conexion);
            JugadorData jd = new JugadorData(conexion);
            Jugador j = (Jugador) jcJugador.getSelectedItem();
        
            
            ArrayList<Patrocinador> patrocinadores = (ArrayList<Patrocinador>) pd.obtenerPatrociniosPosibles(j.getId_jugador());
        
            for(int i = 0; i < patrocinadores.size(); i++){
                jcPatrocinadores.addItem(patrocinadores.get(i));
            }
        
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion " + ex);
        }     
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbPatrocinar;
    private javax.swing.JComboBox<Jugador> jcJugador;
    private javax.swing.JComboBox<Patrocinador> jcPatrocinadores;
    // End of variables declaration//GEN-END:variables
}
