/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torneodetenis.vistas.Torneo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import torneodetenis.control.PatrocinioData;
import torneodetenis.control.RankingData;
import torneodetenis.control.TorneoData;
import torneodetenis.modelo.Conexion;
import torneodetenis.modelo.Jugador;
import torneodetenis.modelo.Ranking;
import torneodetenis.modelo.Torneo;

/**
 *
 * @author Santiago
 */
public class vistaInscribirJugador extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaInscribirJugador
     */
    public vistaInscribirJugador() {
        initComponents();
        jcTorneo.removeAllItems();
        agregarItemTorneo();
        jcJugador.removeAllItems();
        agregarItemJugador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcTorneo = new javax.swing.JComboBox<>();
        jcJugador = new javax.swing.JComboBox<>();
        jbAgregar = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Inscribir Jugador A Torneo");

        jLabel2.setText("Torneo");

        jLabel3.setText("Jugador");

        jcTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTorneoActionPerformed(evt);
            }
        });

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcJugador, 0, 113, Short.MAX_VALUE)
                    .addComponent(jcTorneo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbAgregar)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jbAgregar)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        try{
            Conexion conexion = new Conexion();
            RankingData rd = new RankingData(conexion);
            PatrocinioData pd = new PatrocinioData(conexion);
            
            Jugador j = (Jugador) jcJugador.getSelectedItem();
            Torneo t = (Torneo) jcTorneo.getSelectedItem();
            
            Ranking r = new Ranking(t, j);
            
            rd.inscribirTorneo(r);
            rd.sumarPuntos(r, pd.obtenerNumeroDePatrociniosDeUnJugador(j.getId_jugador()));
            
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion " + ex);
        }
        
        jcJugador.removeAllItems();
        agregarItemJugador();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jcTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTorneoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jcTorneoActionPerformed
    private void agregarItemTorneo(){
        try{
            Conexion conexion = new Conexion();
            TorneoData td = new TorneoData(conexion);
            
            ArrayList<Torneo> torneos = (ArrayList<Torneo>) td.obtenerTorneos();
        
            for(int i = 0; i < torneos.size(); i++){
                jcTorneo.addItem(torneos.get(i));
            }
        
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion " + ex);
        }     
    }
    
    private void agregarItemJugador(){
        try{
            Conexion conexion = new Conexion();
            RankingData rd = new RankingData(conexion);
            Torneo t = (Torneo) jcTorneo.getSelectedItem();
            ArrayList<Jugador> jugadores = (ArrayList<Jugador>) rd.obtenerJugadoresNoInscriptos(t.getId_torneo());
        
            for(int i = 0; i < jugadores.size(); i++){
                jcJugador.addItem(jugadores.get(i));
            }
        
        }catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, "Error en la conexion " + ex);
        }     
    }  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JComboBox<Jugador> jcJugador;
    private javax.swing.JComboBox<Torneo> jcTorneo;
    // End of variables declaration//GEN-END:variables
}
